### ISSUE TITLE
python3 quartet.py CentroMiner -i ref_chr.fa --TE ref_chr.fa.mod.EDTA.intact.gff3      -t 16

### ISSUE THREAD

**Issue by yxx200929** [aaranyue/quarTeT#47]
[Info] Paramater: genomefile=ref_chr.fa, tegfffile=ref_chr.fa.mod.EDTA.intact.gff3, genegfffile=GCA_030267355.1_ASM3026735v1_genomic.gbff.gff, minperiod=100, maxperiod=200, e=1e-05, maxgap=50000, minlength=100000, prefix=quarTeT, threads=16, overwrite=False, noplot=False, match=2, mismatch=7, delta=7, PctMatch=80, PctIndel=10, minscore=50, identity=0.8, periodmaxdelta=10, wordlength=5, max_TR_length=3
[Info] Spliting genome to chromosome...
[Info] Processing each chromosome...
Traceback (most recent call last):
  File "/data2/Dai_lab/yxx/centromere_analysis/Software/quarTeT/quartet_centrominer.py", line 274, in <module>
    quartet_util.run(centroMiner, args)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/data2/Dai_lab/yxx/centromere_analysis/Software/quarTeT/quartet_util.py", line 12, in run
    func(args)
    ~~~~^^^^^^
  File "/data2/Dai_lab/yxx/centromere_analysis/Software/quarTeT/quartet_centrominer.py", line 195, in centroMiner
    p = Pool(min(len(genomedictkey), int(threads)))
  File "/home/bioi/.conda/envs/quartet/lib/python3.13/multiprocessing/dummy/__init__.py", line 124, in Pool
    return ThreadPool(processes, initializer, initargs)
  File "/home/bioi/.conda/envs/quartet/lib/python3.13/multiprocessing/pool.py", line 930, in __init__
    Pool.__init__(self, processes, initializer, initargs)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bioi/.conda/envs/quartet/lib/python3.13/multiprocessing/pool.py", line 205, in __init__
    raise ValueError("Number of processes must be at least 1")
ValueError: Number of processes must be at least 1

**Comment by Echoring** [comment]
It looks like the genome file is not read properly so that sequence number in genome are assumed as 0. Can you check whether the genome file contains non-fasta format content?

**Comment by yxx200929** [comment]
> It looks like the genome file is not read properly so that sequence number in genome are assumed as 0. Can you check whether the genome file contains non-fasta format content?

Thanks for the reply.ref_chr.fa genome fasta file, I just replaced the chromosome ID in that file to give to Chr+number. Finally, after I replaced will original chromosome ID, it works fine.

**Comment by yxx200929** [comment]
Thank you for your timely reply. I will carefully review it and try it out.
Best wishes,
Echoring




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年12月23日(星期一) 上午10:50
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [aaranyue/quarTeT] python3 quartet.py CentroMiner -i ref_chr.fa --TE ref_chr.fa.mod.EDTA.intact.gff3      -t 16 (Issue #47)















看起来基因组文件没有被正确读取，因此基因组中的序列号被假定为0。你能检查基因组文件是否包含非fasta格式的内容吗？

-
直接回复这封邮件，在GitHub上查看它，或者取消订阅.
***@***.*** &gt;

**Comment by mpodio81** [comment]
Hello,
Im trying to run
quartet.py CentroMiner -i scaffold.fa -p CentroMIner_scaffold 

But I have this error. Blast is working in another script, therefore I dont understand why here is not. And there is not candidates.

Thank you.

[Info] Paramater: genomefile=/private/apomixis/SecuenciasPaspalum/Q4117_assembly/Q4117_2025_ragtagySuperscaffold.fa, tegfffile=None, genegfffile=None, minperiod=10, maxperiod=200, e=1e-05, maxgap=50000, minlength=100000,
 prefix=CentroMIner_Q4117yscaffold, threads=1, overwrite=True, noplot=False, match=2, mismatch=7, delta=7, PctMatch=80, PctIndel=10, minscore=50, identity=0.8, periodmaxdelta=10, wordlength=5, max_TR_length=3
[Info] Spliting genome to chromosome...
[Info] Processing each chromosome...
error:  [Errno 2] No such file or directory: 'tmp/blast/CentroMIner_Q4117yscaffold.Chr01.tr.blast'
error:  [Errno 2] No such file or directory: 'tmp/blast/CentroMIner_Q4117yscaffold.Chr02.tr.blast'
error:  [Errno 2] No such file or directory: 'tmp/blast/CentroMIner_Q4117yscaffold.Chr03.tr.blast'
error:  [Errno 2] No such file or directory: 'tmp/blast/CentroMIner_Q4117yscaffold.Chr04.tr.blast'
error:  [Errno 2] No such file or directory: 'tmp/blast/CentroMIner_Q4117yscaffold.Chr05.tr.blast'
error:  [Errno 2] No such file or directory: 'tmp/blast/CentroMIner_Q4117yscaffold.Chr06.tr.blast'
error:  [Errno 2] No such file or directory: 'tmp/blast/CentroMIner_Q4117yscaffold.Chr07.tr.blast'
error:  [Errno 2] No such file or directory: 'tmp/blast/CentroMIner_Q4117yscaffold.Chr08.tr.blast'
error:  [Errno 2] No such file or directory: 'tmp/blast/CentroMIner_Q4117yscaffold.Chr09.tr.blast'
error:  [Errno 2] No such file or directory: 'tmp/blast/CentroMIner_Q4117yscaffold.Chr10.tr.blast'
error:  [Errno 2] No such file or directory: 'tmp/blast/CentroMIner_Q4117yscaffold.Super-Scaffold_361.tr.blast'
error:  [Errno 2] No such file or directory: 'tmp/blast/CentroMIner_Q4117yscaffold.Super-Scaffold_100212.tr.blast'
[Output] Tandem repeats data write to folder: TandemRepeat
[Output] Centromere candidates data write to folder: Candidates
[Info] Complete!
[Info] Time Cost: 0d, 0h, 35m, 42s
